# fly.toml app configuration file generated for attendance-app-v5jdla on 2026-01-20T13:11:28+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'attendance-app-v5jdla'
primary_region = 'bom'

[build]

[env]
  DATABASE_PATH = '/app/data/ovms.db'
  NODE_ENV = 'production'

[[mounts]]
  source = 'visitor_db'
  destination = '/app/data'

[http_service]
  internal_port = 3001
  force_https = true

  # Keep at least 1 machine running to avoid cold starts
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256









